version: "3.2"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  rabbit_mq:
    image: rabbitmq:3.8-rc-management
    hostname: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/var/lib/rabbitmq

  producer:
    build: ./producer
    ports:
      - '5000:5000'
    depends_on:
      - db
      - rabbit_mq
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbit_mq:5672/'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_HOST: 'db'
      DB_NAME: 'inventory'
    volumes:
      - ./producer:/app

  consumer_one:
    build: ./consumer_one
    ports:
      - '5001:5001'
    depends_on:
      - rabbit_mq
      - db
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbit_mq:5672/'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_HOST: 'db'
      DB_NAME: 'inventory'
    volumes:
      - ./consumer_one:/app

  consumer_two:
    build: ./consumer_two
    ports:
      - '5002:5002'
    depends_on:
      - rabbit_mq
      - db
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbit_mq:5672/'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_HOST: 'db'
      DB_NAME: 'inventory'
    volumes:
      - ./consumer_two:/app

  consumer_three:
    build: ./consumer_three
    ports:
      - '5003:5003'
    depends_on:
      - rabbit_mq
      - db
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbit_mq:5672/'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_HOST: 'db'
      DB_NAME: 'inventory'
    volumes:
      - ./consumer_three:/app

  consumer_four:
    build: ./consumer_four
    ports:
      - '5004:5004'
    depends_on:
      - rabbit_mq
      - db
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbit_mq:5672/'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_HOST: 'db'
      DB_NAME: 'inventory'
    volumes:
      - ./consumer_four:/app

volumes:
  dbdata:
    driver: local
  rabbit_mqdata:
    driver: local